type Category = 'Electronics' | 'Vehicles' | 'Accessories';

type CatalogItem = {
    name: string;
    model: string;
    category: Category;
    price: number;
    config: string;
    madeIn: string;
    summary: string;
    tags: string[];
    image: string;
};

const catalog: CatalogItem[] = [
    {
        name: 'Samsung',
        model: 'Galaxy S24 Ultra 5G',
        category: 'Electronics',
        price: 139999,
        config: '12GB RAM, 256GB, Snapdragon 8 Gen 3',
        madeIn: 'Vietnam',
        summary: 'Flagship Android phone with S Pen, Galaxy AI and a 200MP camera.',
        tags: ['smartphone', 'android', 'flagship'],
        image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Apple',
        model: 'iPhone 15 Pro Max',
        category: 'Electronics',
        price: 184999,
        config: '256GB, A17 Pro, Titanium',
        madeIn: 'China',
        summary: 'Premium iPhone with titanium body, Action button and 5x telephoto camera.',
        tags: ['smartphone', 'ios', 'flagship'],
        image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Google',
        model: 'Pixel 8 Pro',
        category: 'Electronics',
        price: 109999,
        config: '12GB RAM, 128GB, Tensor G3',
        madeIn: 'Vietnam',
        summary: 'Google flagship known for computational photography and clean Android.',
        tags: ['smartphone', 'android', 'camera-phone'],
        image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'OnePlus',
        model: 'OnePlus 12',
        category: 'Electronics',
        price: 89999,
        config: '16GB RAM, 512GB, Snapdragon 8 Gen 3',
        madeIn: 'China',
        summary: 'Fast flagship with Hasselblad cameras and 100W charging.',
        tags: ['smartphone', 'android', 'fast-charging'],
        image: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Xiaomi',
        model: 'Xiaomi 14',
        category: 'Electronics',
        price: 84999,
        config: '12GB RAM, 512GB, Leica Camera',
        madeIn: 'China',
        summary: 'Compact flagship featuring Leica optics and a bright LTPO display.',
        tags: ['smartphone', 'android', 'camera-phone'],
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Samsung',
        model: 'Galaxy A55 5G',
        category: 'Electronics',
        price: 51999,
        config: '8GB RAM, 256GB, Exynos 1480',
        madeIn: 'Vietnam',
        summary: 'Balanced mid-range phone with metal frame, OIS and long software support.',
        tags: ['smartphone', 'android', 'midrange'],
        image: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Nothing',
        model: 'Phone (2a)',
        category: 'Electronics',
        price: 39999,
        config: '12GB RAM, 256GB, Dimensity 7200 Pro',
        madeIn: 'India',
        summary: 'Distinctive Android phone with Glyph interface and clean Nothing OS.',
        tags: ['smartphone', 'android', 'midrange'],
        image: 'https://images.unsplash.com/photo-1533228100845-08145b01de14?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Motorola',
        model: 'Edge 50 Fusion',
        category: 'Electronics',
        price: 42999,
        config: '12GB RAM, 256GB, 144Hz OLED',
        madeIn: 'India',
        summary: 'Slim mid-range handset with curved OLED display and rapid charging.',
        tags: ['smartphone', 'android', 'midrange'],
        image: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Realme',
        model: '12 Pro Plus 5G',
        category: 'Electronics',
        price: 46999,
        config: '12GB RAM, 256GB, Periscope Camera',
        madeIn: 'India',
        summary: 'Camera-focused phone with portrait telephoto lens and premium design.',
        tags: ['smartphone', 'android', 'camera-phone'],
        image: 'https://images.unsplash.com/photo-1585060544812-6b45742d762f?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Vivo',
        model: 'V30 5G',
        category: 'Electronics',
        price: 59999,
        config: '12GB RAM, 256GB, 80W Charging',
        madeIn: 'Bangladesh',
        summary: 'Portrait-focused phone with Aura Light and a slim curved design.',
        tags: ['smartphone', 'android', 'portrait'],
        image: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Oppo',
        model: 'Reno 11 5G',
        category: 'Electronics',
        price: 54999,
        config: '12GB RAM, 256GB, Dimensity 7050',
        madeIn: 'Bangladesh',
        summary: 'Stylish Reno-series phone with telephoto portrait camera.',
        tags: ['smartphone', 'android', 'portrait'],
        image: 'https://images.unsplash.com/photo-1567581935884-3349723552ca?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Honor',
        model: 'X9b 5G',
        category: 'Electronics',
        price: 38999,
        config: '12GB RAM, 256GB, 5800mAh',
        madeIn: 'China',
        summary: 'Durable curved-display smartphone with an extra-long battery.',
        tags: ['smartphone', 'android', 'battery'],
        image: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Infinix',
        model: 'Note 40 Pro',
        category: 'Electronics',
        price: 31999,
        config: '8GB RAM, 256GB, 70W Charging',
        madeIn: 'China',
        summary: 'Value-focused phone with AMOLED display and wireless charging support.',
        tags: ['smartphone', 'android', 'value'],
        image: 'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Tecno',
        model: 'Camon 30',
        category: 'Electronics',
        price: 27999,
        config: '8GB RAM, 256GB, 50MP OIS',
        madeIn: 'China',
        summary: 'Affordable camera phone with AMOLED screen and stereo speakers.',
        tags: ['smartphone', 'android', 'value'],
        image: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Nokia',
        model: 'G42 5G',
        category: 'Electronics',
        price: 24999,
        config: '6GB RAM, 128GB, Snapdragon 480+',
        madeIn: 'China',
        summary: 'Repair-friendly 5G phone with dependable battery life.',
        tags: ['smartphone', 'android', 'budget'],
        image: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?q=80&w=1200&auto=format&fit=crop',
    },

    {
        name: 'Apple',
        model: 'MacBook Air 13 M3',
        category: 'Electronics',
        price: 144999,
        config: '8GB Unified Memory, 256GB SSD',
        madeIn: 'China',
        summary: 'Thin and silent everyday laptop powered by Apple M3.',
        tags: ['laptop', 'macbook', 'ultrabook'],
        image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Dell',
        model: 'XPS 13 9340',
        category: 'Electronics',
        price: 174999,
        config: 'Core Ultra 7, 16GB, 512GB SSD',
        madeIn: 'China',
        summary: 'Premium compact Windows laptop with InfinityEdge display.',
        tags: ['laptop', 'windows', 'ultrabook'],
        image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'HP',
        model: 'Spectre x360 14',
        category: 'Electronics',
        price: 169999,
        config: 'Core Ultra 7, 16GB, 1TB SSD, OLED',
        madeIn: 'China',
        summary: 'Convertible premium laptop with OLED touch display and pen support.',
        tags: ['laptop', 'windows', 'convertible'],
        image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Lenovo',
        model: 'ThinkPad E14 Gen 5',
        category: 'Electronics',
        price: 104999,
        config: 'Core i7 13th Gen, 16GB, 512GB SSD',
        madeIn: 'China',
        summary: 'Business laptop with durable chassis and excellent keyboard.',
        tags: ['laptop', 'business', 'windows'],
        image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Asus',
        model: 'ROG Zephyrus G14',
        category: 'Electronics',
        price: 229999,
        config: 'Ryzen 9, 32GB, 1TB SSD, RTX 4070',
        madeIn: 'China',
        summary: 'Portable high-performance gaming laptop with a fast display.',
        tags: ['laptop', 'gaming', 'rtx'],
        image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Acer',
        model: 'Nitro V 15',
        category: 'Electronics',
        price: 124999,
        config: 'Core i5 13th Gen, 16GB, RTX 4050',
        madeIn: 'China',
        summary: 'Affordable gaming laptop for esports and creative workloads.',
        tags: ['laptop', 'gaming', 'windows'],
        image: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'MSI',
        model: 'Katana 15 B13V',
        category: 'Electronics',
        price: 154999,
        config: 'Core i7 13th Gen, 16GB, RTX 4060',
        madeIn: 'China',
        summary: '15-inch gaming laptop with powerful discrete graphics.',
        tags: ['laptop', 'gaming', 'rtx'],
        image: 'https://images.unsplash.com/photo-1595327656903-2f54e37ce09b?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Microsoft',
        model: 'Surface Laptop 5',
        category: 'Electronics',
        price: 134999,
        config: 'Core i5, 8GB, 512GB SSD',
        madeIn: 'China',
        summary: 'Clean, lightweight Windows notebook with PixelSense touchscreen.',
        tags: ['laptop', 'windows', 'touchscreen'],
        image: 'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Huawei',
        model: 'MateBook D 16',
        category: 'Electronics',
        price: 94999,
        config: 'Core i5 13th Gen, 16GB, 512GB SSD',
        madeIn: 'China',
        summary: 'Large-screen productivity laptop in a slim metal chassis.',
        tags: ['laptop', 'productivity', 'windows'],
        image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Walton',
        model: 'Prelude N50 Pro',
        category: 'Electronics',
        price: 52990,
        config: 'Core i5 12th Gen, 8GB, 512GB SSD',
        madeIn: 'Bangladesh',
        summary: 'Locally assembled everyday laptop with service support in Bangladesh.',
        tags: ['laptop', 'local-brand', 'windows'],
        image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=1200&auto=format&fit=crop',
    },

    {
        name: 'Apple',
        model: 'iPad Air 11 M2',
        category: 'Electronics',
        price: 89999,
        config: '128GB, Wi-Fi, Apple M2',
        madeIn: 'China',
        summary: 'Lightweight tablet for study, drawing and portable productivity.',
        tags: ['tablet', 'ipad', 'creative'],
        image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Samsung',
        model: 'Galaxy Tab S9 FE',
        category: 'Electronics',
        price: 57999,
        config: '8GB RAM, 256GB, S Pen',
        madeIn: 'Vietnam',
        summary: 'Water-resistant Android tablet bundled with an S Pen.',
        tags: ['tablet', 'android', 'student'],
        image: 'https://images.unsplash.com/photo-1561154464-82e9adf32764?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Xiaomi',
        model: 'Pad 6',
        category: 'Electronics',
        price: 42999,
        config: '8GB RAM, 256GB, 144Hz Display',
        madeIn: 'China',
        summary: 'High-refresh Android tablet suited to media and productivity.',
        tags: ['tablet', 'android', 'entertainment'],
        image: 'https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Lenovo',
        model: 'Tab P12',
        category: 'Electronics',
        price: 46999,
        config: '8GB RAM, 256GB, 12.7-inch 3K',
        madeIn: 'China',
        summary: 'Large Android tablet designed for entertainment and note-taking.',
        tags: ['tablet', 'android', 'productivity'],
        image: 'https://images.unsplash.com/photo-1527690146636-88b88966f500?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Amazon',
        model: 'Kindle Paperwhite 11th Gen',
        category: 'Electronics',
        price: 21999,
        config: '16GB, 6.8-inch, Waterproof',
        madeIn: 'China',
        summary: 'Glare-free waterproof e-reader with adjustable warm light.',
        tags: ['ereader', 'kindle', 'books'],
        image: 'https://images.unsplash.com/photo-1592496001020-d31bd830651f?q=80&w=1200&auto=format&fit=crop',
    },

    {
        name: 'Samsung',
        model: '55-inch QLED Q70C 4K TV',
        category: 'Electronics',
        price: 119999,
        config: '55-inch, 4K QLED, 120Hz',
        madeIn: 'Bangladesh',
        summary: 'Bright QLED smart TV with smooth motion for movies and gaming.',
        tags: ['tv', 'qled', 'smart-home'],
        image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'LG',
        model: 'C3 55-inch OLED evo TV',
        category: 'Electronics',
        price: 219999,
        config: '55-inch, 4K OLED, webOS',
        madeIn: 'Indonesia',
        summary: 'Premium OLED television with perfect blacks and gaming features.',
        tags: ['tv', 'oled', 'gaming'],
        image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Sony',
        model: 'Bravia X80L 55-inch TV',
        category: 'Electronics',
        price: 134999,
        config: '55-inch, 4K HDR, Google TV',
        madeIn: 'Malaysia',
        summary: 'Natural-colour 4K television powered by Google TV.',
        tags: ['tv', 'google-tv', 'home'],
        image: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'TCL',
        model: 'C645 55-inch QLED TV',
        category: 'Electronics',
        price: 79999,
        config: '55-inch, 4K QLED, Dolby Vision',
        madeIn: 'China',
        summary: 'Value QLED television with Dolby Vision and Google TV.',
        tags: ['tv', 'qled', 'value'],
        image: 'https://images.unsplash.com/photo-1461151304267-38535e780c79?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Walton',
        model: 'W55RUG 55-inch 4K TV',
        category: 'Electronics',
        price: 68990,
        config: '55-inch, 4K UHD, Android TV',
        madeIn: 'Bangladesh',
        summary: 'Locally assembled large-screen Android television.',
        tags: ['tv', 'local-brand', 'android-tv'],
        image: 'https://images.unsplash.com/photo-1577975882846-431adc8c2009?q=80&w=1200&auto=format&fit=crop',
    },

    {
        name: 'Canon',
        model: 'EOS R50 Mirrorless Kit',
        category: 'Electronics',
        price: 89999,
        config: '24.2MP, 18-45mm Lens, 4K',
        madeIn: 'Japan',
        summary: 'Compact mirrorless camera for family photography and content creation.',
        tags: ['camera', 'mirrorless', 'creator'],
        image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Sony',
        model: 'Alpha A6400 Mirrorless Kit',
        category: 'Electronics',
        price: 109999,
        config: '24.2MP, 16-50mm Lens, 4K',
        madeIn: 'Thailand',
        summary: 'Fast autofocus mirrorless camera for travel, portraits and video.',
        tags: ['camera', 'mirrorless', 'creator'],
        image: 'https://images.unsplash.com/photo-1502982720700-befe97b2ff83?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Nikon',
        model: 'Z50 Mirrorless Kit',
        category: 'Electronics',
        price: 114999,
        config: '20.9MP, 16-50mm Lens, 4K',
        madeIn: 'Thailand',
        summary: 'Lightweight Nikon Z camera with excellent handling and colour.',
        tags: ['camera', 'mirrorless', 'photography'],
        image: 'https://images.unsplash.com/photo-1500634245200-e5245c7574ef?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Fujifilm',
        model: 'X-S20 Mirrorless Body',
        category: 'Electronics',
        price: 159999,
        config: '26.1MP, 6.2K Video, IBIS',
        madeIn: 'Japan',
        summary: 'Hybrid photo-video camera with film simulations and stabilization.',
        tags: ['camera', 'mirrorless', 'video'],
        image: 'https://images.unsplash.com/photo-1512790182412-b19e6d62bc39?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'DJI',
        model: 'Osmo Action 4 Adventure Combo',
        category: 'Electronics',
        price: 52999,
        config: '4K 120fps, Waterproof, 3 Batteries',
        madeIn: 'China',
        summary: 'Rugged action camera optimized for low light and outdoor footage.',
        tags: ['camera', 'action-camera', 'travel'],
        image: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?q=80&w=1200&auto=format&fit=crop',
    },

    {
        name: 'Samsung',
        model: 'RT42CG6624S9 Refrigerator',
        category: 'Electronics',
        price: 89999,
        config: '415L, Digital Inverter, Top Mount',
        madeIn: 'Thailand',
        summary: 'Energy-efficient family refrigerator with convertible freezer modes.',
        tags: ['refrigerator', 'appliance', 'home'],
        image: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'LG',
        model: 'T2108VS2M Washing Machine',
        category: 'Electronics',
        price: 48999,
        config: '8kg, Top Load, Smart Inverter',
        madeIn: 'Vietnam',
        summary: 'Automatic top-load washer with energy-saving inverter motor.',
        tags: ['washing-machine', 'appliance', 'home'],
        image: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Gree',
        model: 'GS-18XPUV32 Air Conditioner',
        category: 'Electronics',
        price: 82999,
        config: '1.5 Ton, Inverter, Wi-Fi',
        madeIn: 'China',
        summary: 'Efficient inverter air conditioner sized for a medium room.',
        tags: ['ac', 'appliance', 'cooling'],
        image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Walton',
        model: 'WEO-S28EDK Electric Oven',
        category: 'Electronics',
        price: 13990,
        config: '28L, Convection, Rotisserie',
        madeIn: 'Bangladesh',
        summary: 'Countertop electric oven for baking, grilling and roasting.',
        tags: ['oven', 'kitchen', 'local-brand'],
        image: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Philips',
        model: 'HD9200 Air Fryer',
        category: 'Electronics',
        price: 14999,
        config: '4.1L, Rapid Air, 1400W',
        madeIn: 'China',
        summary: 'Compact air fryer for lower-oil everyday cooking.',
        tags: ['air-fryer', 'kitchen', 'appliance'],
        image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Panasonic',
        model: 'NN-ST34 Microwave Oven',
        category: 'Electronics',
        price: 18999,
        config: '25L, 800W, Digital Control',
        madeIn: 'China',
        summary: 'Solo microwave with practical auto menus and defrost settings.',
        tags: ['microwave', 'kitchen', 'appliance'],
        image: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Singer',
        model: 'SVCB-202 Vacuum Cleaner',
        category: 'Electronics',
        price: 9990,
        config: '2000W, Bagless, HEPA Filter',
        madeIn: 'China',
        summary: 'Powerful bagless vacuum suitable for apartments and family homes.',
        tags: ['vacuum', 'cleaning', 'appliance'],
        image: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Xiaomi',
        model: 'Smart Air Purifier 4',
        category: 'Electronics',
        price: 25999,
        config: '400m³/h, HEPA, App Control',
        madeIn: 'China',
        summary: 'Connected air purifier with particle display and quiet sleep mode.',
        tags: ['air-purifier', 'smart-home', 'appliance'],
        image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Vision',
        model: 'Geyser 45L Prime',
        category: 'Electronics',
        price: 12900,
        config: '45L, 2000W, Safety Valve',
        madeIn: 'Bangladesh',
        summary: 'Storage water heater designed for regular household use.',
        tags: ['geyser', 'home', 'local-brand'],
        image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Kiam',
        model: 'BL-2000 Blender',
        category: 'Electronics',
        price: 5490,
        config: '1000W, 3 Jars, Stainless Blade',
        madeIn: 'Bangladesh',
        summary: 'Multipurpose kitchen blender for spices, smoothies and food preparation.',
        tags: ['blender', 'kitchen', 'local-brand'],
        image: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?q=80&w=1200&auto=format&fit=crop',
    },

    {
        name: 'Yamaha',
        model: 'FZ-S FI V3',
        category: 'Vehicles',
        price: 265000,
        config: '149cc, Fuel Injection, ABS',
        madeIn: 'India',
        summary: 'Comfortable street motorcycle with muscular styling and good economy.',
        tags: ['motorcycle', 'commuter', 'abs'],
        image: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Honda',
        model: 'CB Hornet 2.0',
        category: 'Vehicles',
        price: 289000,
        config: '184.4cc, FI, Single-channel ABS',
        madeIn: 'India',
        summary: 'Sporty commuter motorcycle with responsive engine and agile handling.',
        tags: ['motorcycle', 'street', 'abs'],
        image: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Suzuki',
        model: 'Gixxer SF FI ABS',
        category: 'Vehicles',
        price: 319950,
        config: '155cc, Fuel Injection, ABS',
        madeIn: 'India',
        summary: 'Fully faired everyday sports bike with balanced performance.',
        tags: ['motorcycle', 'sports', 'abs'],
        image: 'https://images.unsplash.com/photo-1599819811279-d5ad9cccf838?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Bajaj',
        model: 'Pulsar N160 FI ABS',
        category: 'Vehicles',
        price: 279900,
        config: '164.8cc, FI, Dual-channel ABS',
        madeIn: 'India',
        summary: 'Modern Pulsar with strong brakes and usable city performance.',
        tags: ['motorcycle', 'street', 'abs'],
        image: 'https://images.unsplash.com/photo-1609630875171-b1321377ee65?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'TVS',
        model: 'Apache RTR 4V FI',
        category: 'Vehicles',
        price: 274999,
        config: '159.7cc, FI, Ride Modes',
        madeIn: 'India',
        summary: 'Feature-rich street bike with race-derived styling and ride modes.',
        tags: ['motorcycle', 'street', 'performance'],
        image: 'https://images.unsplash.com/photo-1615172282427-9a57ef2d142e?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Hero',
        model: 'Thriller 160R 4V',
        category: 'Vehicles',
        price: 239990,
        config: '163.2cc, FI, ABS',
        madeIn: 'India',
        summary: 'Lightweight commuter with sporty design and efficient engine.',
        tags: ['motorcycle', 'commuter', 'abs'],
        image: 'https://images.unsplash.com/photo-1591637333184-19aa84b3e01f?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Royal Enfield',
        model: 'Hunter 350',
        category: 'Vehicles',
        price: 479000,
        config: '349cc, FI, Dual-channel ABS',
        madeIn: 'India',
        summary: 'Accessible retro roadster with relaxed torque and urban handling.',
        tags: ['motorcycle', 'retro', 'roadster'],
        image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'KTM',
        model: 'Duke 200 ABS',
        category: 'Vehicles',
        price: 465000,
        config: '199.5cc, Liquid Cooled, ABS',
        madeIn: 'India',
        summary: 'Sharp naked motorcycle with energetic performance and premium hardware.',
        tags: ['motorcycle', 'naked', 'performance'],
        image: 'https://images.unsplash.com/photo-1571188654248-7a89213915f7?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Lifan',
        model: 'KPR 165R EFI',
        category: 'Vehicles',
        price: 249000,
        config: '165cc, EFI, Liquid Cooled',
        madeIn: 'China',
        summary: 'Affordable faired sports motorcycle with a liquid-cooled engine.',
        tags: ['motorcycle', 'sports', 'efi'],
        image: 'https://images.unsplash.com/photo-1547549082-6bc09f2049ae?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'CFMoto',
        model: '300SR',
        category: 'Vehicles',
        price: 458500,
        config: '292cc, EFI, Dual-channel ABS',
        madeIn: 'China',
        summary: 'Entry-level sport bike with modern electronics and full fairing.',
        tags: ['motorcycle', 'sports', 'abs'],
        image: 'https://images.unsplash.com/photo-1591737648342-e1a533baaa74?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Keeway',
        model: 'RKS 150 Sports',
        category: 'Vehicles',
        price: 149900,
        config: '149cc, Carburetor, Disc Brake',
        madeIn: 'China',
        summary: 'Budget-friendly commuter with upright ergonomics and simple maintenance.',
        tags: ['motorcycle', 'commuter', 'budget'],
        image: 'https://images.unsplash.com/photo-1525160354320-d8e92641c563?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Runner',
        model: 'Bolt 165R',
        category: 'Vehicles',
        price: 179000,
        config: '165cc, Disc Brake, 5 Speed',
        madeIn: 'Bangladesh',
        summary: 'Locally assembled sporty commuter backed by a national service network.',
        tags: ['motorcycle', 'local-brand', 'commuter'],
        image: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'GPX',
        model: 'Demon GR165R',
        category: 'Vehicles',
        price: 374999,
        config: '164.6cc, 6 Speed, ABS',
        madeIn: 'Thailand',
        summary: 'Compact fully faired motorcycle with aggressive mini-sport styling.',
        tags: ['motorcycle', 'sports', 'abs'],
        image: 'https://images.unsplash.com/photo-1609630875171-b1321377ee65?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Aprilia',
        model: 'GPR 150 ABS',
        category: 'Vehicles',
        price: 395000,
        config: '149cc, Liquid Cooled, ABS',
        madeIn: 'China',
        summary: 'Track-inspired lightweight sport bike with an aluminium frame.',
        tags: ['motorcycle', 'sports', 'premium'],
        image: 'https://images.unsplash.com/photo-1558980664-769d59546b3d?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Honda',
        model: 'Dio 110',
        category: 'Vehicles',
        price: 199000,
        config: '109.5cc, Automatic, CBS',
        madeIn: 'India',
        summary: 'Easy-to-ride automatic scooter for daily city travel.',
        tags: ['scooter', 'commuter', 'automatic'],
        image: 'https://images.unsplash.com/photo-1609630875171-b1321377ee65?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Yamaha',
        model: 'RayZR Street Rally 125',
        category: 'Vehicles',
        price: 270000,
        config: '125cc, Hybrid, FI',
        madeIn: 'India',
        summary: 'Light hybrid scooter with rugged styling and efficient city performance.',
        tags: ['scooter', 'hybrid', 'automatic'],
        image: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Suzuki',
        model: 'Access 125',
        category: 'Vehicles',
        price: 205000,
        config: '124cc, FI, Combined Brake',
        madeIn: 'India',
        summary: 'Practical family scooter with spacious storage and smooth power.',
        tags: ['scooter', 'family', 'automatic'],
        image: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'TVS',
        model: 'Ntorq 125 Race Edition',
        category: 'Vehicles',
        price: 214900,
        config: '124.8cc, Bluetooth, Automatic',
        madeIn: 'India',
        summary: 'Sporty connected scooter with navigation display and strong acceleration.',
        tags: ['scooter', 'connected', 'automatic'],
        image: 'https://images.unsplash.com/photo-1615172282427-9a57ef2d142e?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Phoenix',
        model: 'Tornado 27.5 MTB',
        category: 'Vehicles',
        price: 28500,
        config: '27.5-inch, 21 Speed, Disc Brake',
        madeIn: 'China',
        summary: 'Geared mountain bicycle for commuting and weekend trails.',
        tags: ['bicycle', 'mountain-bike', 'fitness'],
        image: 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Duranta',
        model: 'Steel 2.0 City Bicycle',
        category: 'Vehicles',
        price: 16500,
        config: '26-inch, Single Speed, Carrier',
        madeIn: 'Bangladesh',
        summary: 'Durable locally made bicycle for regular urban commuting.',
        tags: ['bicycle', 'commuter', 'local-brand'],
        image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=1200&auto=format&fit=crop',
    },

    {
        name: 'Sony',
        model: 'WH-1000XM5 Headphones',
        category: 'Accessories',
        price: 42999,
        config: 'ANC, Bluetooth 5.2, 30-hour Battery',
        madeIn: 'Malaysia',
        summary: 'Premium wireless headphones with class-leading noise cancellation.',
        tags: ['headphones', 'audio', 'anc'],
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Bose',
        model: 'QuietComfort Ultra Headphones',
        category: 'Accessories',
        price: 54999,
        config: 'ANC, Immersive Audio, 24-hour Battery',
        madeIn: 'Thailand',
        summary: 'Comfortable flagship headphones with immersive spatial audio.',
        tags: ['headphones', 'audio', 'anc'],
        image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Sennheiser',
        model: 'Momentum 4 Wireless',
        category: 'Accessories',
        price: 39999,
        config: 'Adaptive ANC, 60-hour Battery',
        madeIn: 'China',
        summary: 'Audiophile-leaning wireless headphones with exceptional battery life.',
        tags: ['headphones', 'audio', 'wireless'],
        image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Apple',
        model: 'AirPods Pro 2nd Gen USB-C',
        category: 'Accessories',
        price: 29999,
        config: 'ANC, MagSafe Case, USB-C',
        madeIn: 'Vietnam',
        summary: 'Noise-cancelling earbuds with seamless Apple device integration.',
        tags: ['earbuds', 'apple', 'anc'],
        image: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Samsung',
        model: 'Galaxy Buds2 Pro',
        category: 'Accessories',
        price: 16999,
        config: 'ANC, 24-bit Audio, IPX7',
        madeIn: 'Vietnam',
        summary: 'Compact premium earbuds tuned for Samsung Galaxy devices.',
        tags: ['earbuds', 'samsung', 'anc'],
        image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'OnePlus',
        model: 'Buds 3',
        category: 'Accessories',
        price: 11999,
        config: 'ANC, Dual Drivers, 44-hour Battery',
        madeIn: 'China',
        summary: 'Value wireless earbuds with strong sound and effective ANC.',
        tags: ['earbuds', 'audio', 'value'],
        image: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'JBL',
        model: 'Tune Beam',
        category: 'Accessories',
        price: 9999,
        config: 'ANC, IP54, 48-hour Battery',
        madeIn: 'China',
        summary: 'Bass-forward true wireless earbuds for commuting and workouts.',
        tags: ['earbuds', 'audio', 'wireless'],
        image: 'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'JBL',
        model: 'Flip 6 Portable Speaker',
        category: 'Accessories',
        price: 13999,
        config: '30W, IP67, 12-hour Battery',
        madeIn: 'China',
        summary: 'Rugged portable Bluetooth speaker with balanced room-filling sound.',
        tags: ['speaker', 'audio', 'portable'],
        image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Marshall',
        model: 'Emberton II Speaker',
        category: 'Accessories',
        price: 22999,
        config: 'IP67, 30-hour Battery, Stack Mode',
        madeIn: 'China',
        summary: 'Stylish portable speaker with wide stereo sound and long battery life.',
        tags: ['speaker', 'audio', 'portable'],
        image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Harman Kardon',
        model: 'Aura Studio 3',
        category: 'Accessories',
        price: 34999,
        config: '130W, Bluetooth, Ambient Light',
        madeIn: 'China',
        summary: 'Distinctive home Bluetooth speaker with rich bass and ambient lighting.',
        tags: ['speaker', 'audio', 'home'],
        image: 'https://images.unsplash.com/photo-1543512214-318c7553f230?q=80&w=1200&auto=format&fit=crop',
    },

    {
        name: 'Anker',
        model: '737 Power Bank 24000mAh',
        category: 'Accessories',
        price: 17999,
        config: '140W USB-C PD, Smart Display',
        madeIn: 'China',
        summary: 'High-output power bank capable of charging laptops and phones.',
        tags: ['power-bank', 'charger', 'travel'],
        image: 'https://images.unsplash.com/photo-1609592807664-84d2843818e6?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Baseus',
        model: 'Blade 100W Power Bank',
        category: 'Accessories',
        price: 9999,
        config: '20000mAh, 100W PD, Display',
        madeIn: 'China',
        summary: 'Slim laptop-capable power bank with live charging display.',
        tags: ['power-bank', 'charger', 'usb-c'],
        image: 'https://images.unsplash.com/photo-1619725002198-6a689b72f41d?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'UGREEN',
        model: 'Nexode 65W GaN Charger',
        category: 'Accessories',
        price: 5999,
        config: '65W, 2 USB-C + USB-A',
        madeIn: 'China',
        summary: 'Compact multi-port charger for phones, tablets and ultrabooks.',
        tags: ['charger', 'gan', 'usb-c'],
        image: 'https://images.unsplash.com/photo-1615526675159-e248c3021d3f?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Apple',
        model: '20W USB-C Power Adapter',
        category: 'Accessories',
        price: 2999,
        config: '20W USB-C PD',
        madeIn: 'China',
        summary: 'Official compact fast charger for iPhone and iPad.',
        tags: ['charger', 'apple', 'usb-c'],
        image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Samsung',
        model: '45W Super Fast Charger',
        category: 'Accessories',
        price: 4499,
        config: '45W USB-C PD PPS, Cable Included',
        madeIn: 'Vietnam',
        summary: 'Official fast charger for compatible Galaxy phones and tablets.',
        tags: ['charger', 'samsung', 'usb-c'],
        image: 'https://images.unsplash.com/photo-1622445262464-84b1456045b6?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Baseus',
        model: 'Crystal Shine USB-C Cable 100W',
        category: 'Accessories',
        price: 1099,
        config: '2m, 100W PD, Braided',
        madeIn: 'China',
        summary: 'Durable high-power braided cable with charging indicator.',
        tags: ['cable', 'usb-c', 'charging'],
        image: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Anker',
        model: 'PowerLine III USB-C Cable',
        category: 'Accessories',
        price: 1499,
        config: '1.8m, 100W, Nylon Braided',
        madeIn: 'China',
        summary: 'Reliable high-speed charging cable with reinforced construction.',
        tags: ['cable', 'usb-c', 'charging'],
        image: 'https://images.unsplash.com/photo-1541689592655-f5f52825a3b8?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Belkin',
        model: 'BoostCharge 3-in-1 Wireless Pad',
        category: 'Accessories',
        price: 16999,
        config: '15W Qi2, Phone + Watch + Earbuds',
        madeIn: 'China',
        summary: 'Single charging station for three compatible personal devices.',
        tags: ['wireless-charger', 'qi2', 'desk'],
        image: 'https://images.unsplash.com/photo-1622445262464-84b1456045b6?q=80&w=1200&auto=format&fit=crop',
    },

    {
        name: 'Arctic Hunter',
        model: 'B00382 Laptop Backpack',
        category: 'Accessories',
        price: 5499,
        config: '15.6-inch, Water Resistant, USB Port',
        madeIn: 'China',
        summary: 'Organized commuter backpack with padded laptop compartment.',
        tags: ['backpack', 'laptop', 'travel'],
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'American Tourister',
        model: 'Kamden 02 Backpack',
        category: 'Accessories',
        price: 6999,
        config: '25L, 15.6-inch Laptop Sleeve',
        madeIn: 'India',
        summary: 'Durable branded backpack for office, university and travel.',
        tags: ['backpack', 'travel', 'laptop'],
        image: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Herschel',
        model: 'Little America Backpack 25L',
        category: 'Accessories',
        price: 12499,
        config: '25L, Padded 15-inch Sleeve',
        madeIn: 'Vietnam',
        summary: 'Classic mountaineering-style everyday backpack with modern storage.',
        tags: ['backpack', 'fashion', 'travel'],
        image: 'https://images.unsplash.com/photo-1577733966973-d680bffd2e80?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Aarong',
        model: 'Genuine Leather Bifold Wallet',
        category: 'Accessories',
        price: 2450,
        config: 'Leather, 8 Card Slots, Coin Pocket',
        madeIn: 'Bangladesh',
        summary: 'Locally crafted leather wallet with practical everyday storage.',
        tags: ['wallet', 'leather', 'local-brand'],
        image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Spigen',
        model: 'Ultra Hybrid iPhone 15 Pro Case',
        category: 'Accessories',
        price: 2499,
        config: 'Clear TPU, Air Cushion Protection',
        madeIn: 'South Korea',
        summary: 'Protective clear phone case that preserves the original device design.',
        tags: ['phone-case', 'iphone', 'protection'],
        image: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Ringke',
        model: 'Fusion X Galaxy S24 Ultra Case',
        category: 'Accessories',
        price: 2199,
        config: 'Hybrid Armor, Lanyard Holes',
        madeIn: 'South Korea',
        summary: 'Rugged transparent case with reinforced corners and secure grip.',
        tags: ['phone-case', 'samsung', 'protection'],
        image: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Xiaomi',
        model: 'Smart Band 8',
        category: 'Accessories',
        price: 4999,
        config: 'AMOLED, 150+ Sports Modes, 16 Days',
        madeIn: 'China',
        summary: 'Slim fitness tracker with bright display and long battery life.',
        tags: ['fitness-band', 'wearable', 'health'],
        image: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?q=80&w=1200&auto=format&fit=crop',
    },

    {
        name: 'Logitech',
        model: 'MX Master 3S Mouse',
        category: 'Accessories',
        price: 13999,
        config: '8K DPI, Quiet Clicks, Bluetooth',
        madeIn: 'China',
        summary: 'Premium productivity mouse with precise scrolling and multi-device control.',
        tags: ['mouse', 'computer', 'productivity'],
        image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Logitech',
        model: 'K380 Bluetooth Keyboard',
        category: 'Accessories',
        price: 4499,
        config: 'Compact, 3 Devices, Bluetooth',
        madeIn: 'China',
        summary: 'Portable multi-device keyboard for computers, tablets and phones.',
        tags: ['keyboard', 'computer', 'bluetooth'],
        image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Keychron',
        model: 'K2 V2 Mechanical Keyboard',
        category: 'Accessories',
        price: 9999,
        config: '75%, Hot-swappable, RGB, Wireless',
        madeIn: 'China',
        summary: 'Compact mechanical keyboard that works with Windows and macOS.',
        tags: ['keyboard', 'mechanical', 'computer'],
        image: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Razer',
        model: 'DeathAdder V3 Gaming Mouse',
        category: 'Accessories',
        price: 8999,
        config: '30K DPI, 59g, Optical Switches',
        madeIn: 'China',
        summary: 'Lightweight ergonomic gaming mouse with a high-precision sensor.',
        tags: ['mouse', 'gaming', 'computer'],
        image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?q=80&w=1200&auto=format&fit=crop',
    },
    {
        name: 'Baseus',
        model: 'Metal Gleam II 10-in-1 USB-C Hub',
        category: 'Accessories',
        price: 7499,
        config: '4K HDMI, Ethernet, 100W PD, Card Reader',
        madeIn: 'China',
        summary: 'Versatile USB-C expansion hub for laptops and tablets.',
        tags: ['usb-hub', 'computer', 'usb-c'],
        image: 'https://images.unsplash.com/photo-1544652478-6653e09f18a2?q=80&w=1200&auto=format&fit=crop',
    },
];

const discountCycle = [8, 10, 12, 15, 18, 20, 22, 25];

const includesTag = (item: CatalogItem, tag: string) => item.tags.includes(tag);

function labelForValue(item: CatalogItem, value: string, index: number): string {
    if (/\b(core|ryzen|snapdragon|tensor|dimensity|exynos|apple m\d|a17 pro)\b/i.test(value))
        return 'Processor';
    if (/\b\d+gb\s+(ram|unified memory|memory)\b/i.test(value)) return 'Memory';
    if (/\b\d+(gb|tb)\s*(ssd|storage)?\b/i.test(value) && !/ram|memory/i.test(value))
        return 'Storage';
    if (/\brtx\s*\d+/i.test(value)) return 'Graphics';
    if (/\b\d+(\.\d+)?\s*-?inch\b/i.test(value))
        return includesTag(item, 'bicycle') ? 'Wheel Size' : 'Screen Size';
    if (/\b(oled|amoled|qled|ltpo|pixelsense|3k|4k uhd)\b/i.test(value)) return 'Display';
    if (/\b\d+hz\b/i.test(value)) return 'Refresh Rate';
    if (/\b\d+(\.\d+)?mp\b/i.test(value)) return 'Camera / Sensor';
    if (/\b\d+-\d+mm\s+lens\b/i.test(value)) return 'Included Lens';
    if (/\b(4k|6\.2k)\b/i.test(value)) return 'Video Recording';
    if (/\b\d+(\.\d+)?cc\b/i.test(value)) return 'Engine Displacement';
    if (/\b(abs|cbs|combined brake|disc brake)\b/i.test(value)) return 'Braking System';
    if (/\b(fuel injection|fi|efi|carburetor)\b/i.test(value)) return 'Fuel System';
    if (/\b(automatic|\d+ speed)\b/i.test(value)) return 'Transmission';
    if (/\b\d+mah\b/i.test(value)) return 'Battery Capacity';
    if (/\b\d+(-hour|\s*hours?|\s*days?)\b/i.test(value)) return 'Battery Life';
    if (/\banc\b|noise cancellation/i.test(value)) return 'Noise Cancellation';
    if (/bluetooth/i.test(value)) return 'Connectivity';
    if (/\bip\d{2}\b|waterproof|water resistant/i.test(value)) return 'Ingress Protection';
    if (/\b\d+(\.\d+)?l\b/i.test(value)) return 'Capacity';
    if (/\b\d+(\.\d+)?kg\b/i.test(value)) return 'Load Capacity';
    if (/inverter/i.test(value)) return 'Motor / Compressor';
    if (/\b\d+w\b|power delivery|\bpd\b/i.test(value)) return 'Power / Charging Output';
    if (/hdmi/i.test(value)) return 'Video Output';
    if (/ethernet/i.test(value)) return 'Network';
    if (/card reader/i.test(value)) return 'Card Reader';
    if (/usb|ports?/i.test(value)) return 'Ports';
    if (/dpi/i.test(value)) return 'Sensor Resolution';
    if (/hot-swappable|optical switches/i.test(value)) return 'Switch Type';
    if (/rgb/i.test(value)) return 'Lighting';
    if (/leather|nylon|tpu|metal frame/i.test(value)) return 'Material';
    if (/card slots?|laptop sleeve/i.test(value)) return 'Storage / Compatibility';
    if (/air cushion|armor|protection/i.test(value)) return 'Protection';
    if (/wi-fi|google tv|android tv|webos|app control/i.test(value)) return 'Smart Platform';
    return ['Primary Feature', 'Technology', 'Additional Feature', 'Included Feature'][
        Math.min(index, 3)
    ];
}

function buildSpecifications(item: CatalogItem): Record<string, string> {
    const values = item.config.split(',').map((value) => value.trim());
    const specifications: Record<string, string> = {};

    values.forEach((value, index) => {
        const label = labelForValue(item, value, index);
        specifications[label] = specifications[label]
            ? `${specifications[label]}, ${value}`
            : value;
    });

    specifications['Country of Origin'] = item.madeIn;
    specifications.Warranty =
        item.category === 'Vehicles'
            ? 'Brand or authorized dealer warranty; coverage varies by model'
            : item.category === 'Electronics'
              ? '12-month seller or manufacturer warranty, subject to listing terms'
              : '6-month seller warranty, subject to listing terms';
    return specifications;
}

function useCase(item: CatalogItem): string {
    if (includesTag(item, 'smartphone'))
        return 'It is suited to communication, photography, entertainment and everyday app use.';
    if (includesTag(item, 'laptop'))
        return includesTag(item, 'gaming')
            ? 'Its processor and dedicated graphics are intended for gaming, creative applications and demanding multitasking.'
            : 'It is designed for office work, study, video meetings and everyday productivity.';
    if (includesTag(item, 'tablet') || includesTag(item, 'ereader'))
        return 'The portable form factor works well for reading, media, study and light productivity.';
    if (includesTag(item, 'tv'))
        return 'The panel and smart platform are intended for streaming, sports, films and console use.';
    if (includesTag(item, 'camera'))
        return 'It is a practical choice for travel, family photography and content production.';
    if (item.category === 'Vehicles')
        return 'The specification balances regular commuting, rider comfort and practical ownership in Bangladesh.';
    if (
        includesTag(item, 'headphones') ||
        includesTag(item, 'earbuds') ||
        includesTag(item, 'speaker')
    )
        return 'It is suitable for music, calls, travel and daily listening.';
    if (
        includesTag(item, 'charger') ||
        includesTag(item, 'power-bank') ||
        includesTag(item, 'cable')
    )
        return 'It is intended for dependable charging at home, at work and while travelling.';
    return 'The design focuses on practical everyday use, compatibility and durability.';
}

function buildDescription(item: CatalogItem): string {
    const subject = `${item.name} ${item.model}`;
    return [
        `${subject}: ${item.summary}`,
        `Its main configuration is ${item.config}. ${useCase(item)}`,
        `This listing records ${item.madeIn} as the country of origin. Package contents, colour availability and exact warranty coverage should be confirmed from the seller before purchase.`,
    ].join('\n\n');
}

export const seedProducts = catalog.map((item, index) => {
    const { image, summary, ...product } = item;
    const discountPercent = discountCycle[index % discountCycle.length];
    const originalPrice = Math.ceil(item.price / (1 - discountPercent / 100) / 10) * 10;

    return {
        ...product,
        img: image,
        description: buildDescription({ ...item, summary }),
        specifications: buildSpecifications(item),
        originalPrice,
        stock: item.category === 'Vehicles' ? 2 + (index % 9) : 8 + ((index * 17) % 93),
        images: [image],
        isFeatured: index % 9 === 0,
        isFlashDeal: index % 7 === 0,
        discountPercent,
        isNewArrival: index % 6 === 0,
    };
});

if (seedProducts.length !== 100) {
    throw new Error(`Expected 100 seed products, found ${seedProducts.length}`);
}
